import type { Metadata } from "next";
import "./globals.css";
import { outfit } from "./config/fonts/outfit";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased flex flex-col items-center bg-background px-10 sm:px-20 md:px-44 xl:px-96`}
      >
        {children}
      </body>
    </html>
  );
}
